include:
  - ./compose/postgres.yml
  - ./compose/redis.yml
  - ./compose/redis-insight.yml

services: {}

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  redis_insight:
    driver: local

networks:
  showdown-network:
    driver: bridge
